### ISSUE TITLE
Tiros 1 impossible with Remote tech

### ISSUE THREAD

**Issue by thghca** [malkuth1974/MissionController2#30]
It was fixed for Tiros 2 here:
https://github.com/malkuth1974/MissionController2/blob/4a2de27121a25a49df2abdd29c55cfde7a6357b1/MissionControllerEC/MCEContracts/HistoricContracts.cs#L557
But not for Tiros 1:
https://github.com/malkuth1974/MissionController2/blob/4a2de27121a25a49df2abdd29c55cfde7a6357b1/MissionControllerEC/MCEContracts/HistoricContracts.cs#L566

**Comment by malkuth1974** [comment]
This issue has been solved newest versions.
