### ISSUE TITLE
Version file missing

### ISSUE THREAD

**Issue by HebaruSan** [malkuth1974/MissionController2#31]
This mod used to have a version file, but the latest release doesn't. This will cause it to be marked as compatible with all KSP versions in CKAN, which probably isn't correct given that it contains a dll file.

Noticed while working on KSP-CKAN/NetKAN#8018.

Tagging @malkuth1974 because GitHub notifications are not reliable for pull requests.

**Comment by malkuth1974** [comment]
thanks.. Added version file back.
